export const DATA_TABLEAU_MODIFIABLE = [
  {
    serveur: 'ADELAIDE1',
    systeme: 'Windows',
    nom: 'Serveur ADELAIDE 1 de production Windows',
    ip: 'cnp30preadelaide1.cer30.recouv',
    test: 'Testé',
    etat: 'Inactif',
    date: '2022-01-06T10:00:00.000Z',
    lockEdition: true
  },
  {
    serveur: 'ADELAIDE2',
    systeme: 'Windows',
    nom: 'Serveur ADELAIDE 2 de production Windows',
    ip: 'cnp30preadelaide2.cer30.recouv',
    test: 'Testé',
    etat: 'Inactif',
    date: '2022-01-07T10:00:00.000Z'
  },
  {
    serveur: 'ADELAIDE3',
    systeme: 'Windows',
    nom: 'Serveur ADELAIDE 3 de production Windows',
    ip: 'cnp30preadelaide3.cer30.recouv',
    test: 'Testé',
    etat: 'Inactif',
    date: '2022-01-08T10:00:00.000Z',
  },
  {
    serveur: 'GRH31GID',
    systeme: 'Linux',
    nom: 'Serveur GRH',
    ip: 'grh31gidnscop.cer31.recouv',
    test: 'Testé',
    etat: 'Actif',
    date: '2022-01-10T10:00:00.000Z',
  },
  {
    serveur: 'IMAGE090',
    systeme: 'Linux',
    nom: 'Serveur image ur090',
    ip: 'UR090IMAGE.UR090.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE092',
    systeme: 'MacOS',
    nom: 'Serveur image ur092',
    ip: 'UR092IMAGE.UR092.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE120',
    systeme: 'Linux',
    nom: 'Serveur image ur120',
    ip: 'UR0120IMAGE.UR120.RECOUV',
    test: '-',
    etat: 'Inactif',
  },
  {
    serveur: 'IMAGE140',
    systeme: 'Linux',
    nom: 'Serveur image ur140',
    ip: 'UR140IMAGE.UR140.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE160',
    systeme: 'MacOS',
    nom: 'Serveur image ur160',
    ip: 'UR160IMAGE.UR160.RECOUV',
    test: 'Testé',
    etat: 'Inactif',
    date: '2022-01-11T10:00:00.000Z',
  },
  {
    serveur: 'IMAGE170',
    systeme: 'MacOS',
    nom: 'Serveur image ur170',
    ip: 'UR170IMAGE.UR170.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE172',
    systeme: 'Linux',
    nom: 'Serveur image ur172',
    ip: 'UR172IMAGE.UR172.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE175',
    systeme: 'Linux',
    nom: 'Serveur image ur172',
    ip: 'UR172IMAGE.UR172.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'ADELAIDE4',
    systeme: 'Windows',
    nom: 'Serveur ADELAIDE 4 de production Windows',
    ip: 'cnp40preadelaide4.cer40.recouv',
    test: 'Testé',
    etat: 'Inactif',
    date: '2022-01-22T10:00:00.000Z',
  },
  {
    serveur: 'IMAGE190',
    systeme: 'MacOS',
    nom: 'Serveur image ur190',
    ip: 'UR190IMAGE.UR190.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE220',
    systeme: 'MacOS',
    nom: 'Serveur image ur220',
    ip: 'UR220IMAGE.UR220.RECOUV',
    test: '-',
    etat: 'Actif',
  },
  {
    serveur: 'IMAGE230',
    systeme: 'Linux',
    nom: 'Serveur image ur230',
    ip: 'UR230IMAGE.UR230.RECOUV',
    test: '-',
    etat: 'Inactif',
  },
  {
    serveur: 'IMAGE237',
    systeme: 'MacOS',
    nom: 'image ur237',
    ip: 'UR237IMAGE.UR237.RECOUV',
    test: '-',
    etat: 'Actif',
  }
];
