
export const DATA_TABLEAU_PJD_DETAIL = [
  {
    ctp: '012',
    nature: 'Forfait social taux 20%',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: '',
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '027',
    nature: 'Contribution au dialogue social',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 73214,
    taux: 0.016,
    montant: 12,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 12
  },
  {
    ctp: '100',
    nature: 'RG cas général',
    format: 'X',
    codeRisque: '748GB',
    codeCommune: '',
    assiette: 73214,
    taux: 22.16,
    montant: 16224,
    assiette2: 71877,
    taux2: 15.45,
    montant2: '',
    montantTotal: 16224
  },
  {
    ctp: '100',
    nature: 'RG cas général',
    format: 'X',
    codeRisque: '516LC',
    codeCommune: '',
    assiette: '',
    taux: 2.40,
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '100',
    nature: 'CSG CRDS Régime général',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 29,
    taux: 9.70,
    montant: 3,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 3
  },
  {
    ctp: '400',
    nature: 'Crédit impôt',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 70113,
    taux: '',
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '430',
    nature: 'Complément cotisation AF',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 1931,
    taux: 1.80,
    montant: 35,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 35
  },
  {
    ctp: '437',
    nature: 'Déduction AF taux réduit',
    format: 'F',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: '',
    montant: '',
    assiette2: '',
    taux2: 100,
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '450',
    nature: 'Complément cotisation universelle',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: 0.01,
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '451',
    nature: 'Pénibilité cot. addit. mono expo.',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: 0.20,
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '479',
    nature: 'Forfait social 8%',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 29,
    taux: 8,
    montant: 2,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 2
  },
  {
    ctp: '671',
    nature: 'Réduction générale',
    format: 'F',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: '',
    montant: '',
    assiette2: 12949,
    taux2: 100,
    montant2: 12949,
    montantTotal: 12949
  },
  {
    ctp: '719',
    nature: 'Contrib. Indemité mise à la retraite',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: 50,
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '772',
    nature: 'Contributions assurance chômage',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 73214,
    taux: 5,
    montant: 3661,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 3661
  },
  {
    ctp: '801',
    nature: 'Régul. réduction générale',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: '',
    taux: '',
    montant: '',
    assiette2: '',
    taux2: 100,
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '900',
    nature: 'Transport',
    format: 'X',
    codeRisque: '',
    codeCommune: 38336,
    assiette: '',
    taux: '',
    montant: '',
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: ''
  },
  {
    ctp: '902',
    nature: 'Transport taux multiples',
    format: 'X',
    codeRisque: '',
    codeCommune: 38300,
    assiette: '',
    taux: '',
    montant: '',
    assiette2: 16,
    taux2: 100,
    montant2: 16,
    montantTotal: 16
  },
  {
    ctp: '903',
    nature: 'Taxe synd. mixte tx multiples transp.',
    format: 'X',
    codeRisque: '',
    codeCommune: 'Multiple',
    assiette: '',
    taux: '',
    montant: '',
    assiette2: -2,
    taux2: 100,
    montant2: -2,
    montantTotal: -2
  },
  {
    ctp: '937',
    nature: 'Cotisations AGS cas général',
    format: 'X',
    codeRisque: '',
    codeCommune: '',
    assiette: 73214,
    taux: 15,
    montant: 10982,
    assiette2: '',
    taux2: '',
    montant2: '',
    montantTotal: 10982
  }
];
